### ISSUE TITLE
ChatGPT assistant is providing blank responses

### ISSUE THREAD

**Issue by pauldburton** [wavebox/wavebox-flow#2]
I am running wavebox and trying to use the flow process.
![image](https://github.com/wavebox/wavebox-flow/assets/974275/1346a52c-8eef-4e62-8147-9e92ceb0f536)

When I ask it a question, the response is blank.
![image](https://github.com/wavebox/wavebox-flow/assets/974275/d122a053-90b9-457a-8fed-aef1dad0177f)

But when I use one of the example prompts it returns a response
![image](https://github.com/wavebox/wavebox-flow/assets/974275/7b188cea-e502-49e4-ad30-ad04f9a12f10)

Not sure what i can provide to help diagnose this.

Also if I ask it to check the code for errors, the same response
![image](https://github.com/wavebox/wavebox-flow/assets/974275/213a402b-5a05-4b31-9207-5048617031c4)

**Comment by Thomas101** [comment]
Hi, thanks for reporting. It should be working again now 👍
